ucgmsim/gmhazard

apis/core_api/core_api/api/gms.py
apis/project_api/project_api/api/gms.py
apis/project_api/project_api/utils.py
calculation/seistech_calc/seistech_calc/gms/gms.py
tools/project_gen/project_gen/gms.py
tools/seistech_utils/seistech_utils/src/api/shared_responses.py

Made sure that project and core api display the same information for a GMS compute response.
Project generation changes to store disagg result. (Tried to test this but having some local issues I presume)

GMS metadata json changes

---

apis/project_api/CHANGELOG.md
apis/project_api/setup.py
calculation/seistech_calc/seistech_calc/disagg/disagg.py
calculation/seistech_calc/seistech_calc/gm_data/Ensemble.py
calculation/seistech_calc/seistech_calc/gm_data/IMEnsemble.py
calculation/seistech_calc/seistech_calc/hazard/hazard.py
calculation/seistech_calc/seistech_calc/plots/gmt_plotting.py
tools/project_gen/CHANGELOG.md
tools/project_gen/project_gen/__init__.py
tools/project_gen/project_gen/project.py
tools/project_gen/project_gen/psha.py
tools/project_gen/project_gen/scripts/run_project_creation.py
tools/project_gen/setup.py

+ disagg computation improvements
+ IMEnsemble rupture_df generation improvements

CFM support 

---

apis/core_api/core_api/api/nzta.py

Missed one commit from the old SeisTech repo.

Missing import

---

apis/core_api/requirements.txt
tools/seistech_scripts/db_creation/im_csv_to_imdb.py
tools/seistech_scripts/verification/hazard_maps/gen_hazard_map_script_config.yaml
tools/seistech_scripts/verification/hazard_maps/plot_maps.py
tools/seistech_utils/seistech_utils/src/utils.py

- A few changes to im csv to imdb to allow for specifying a component.
- Fix in utils with importing os
- Updates to some configs

Cs 21p6 changes

---

apis/core_api/core_api/api/gms.py
frontend/CHANGELOG.md
frontend/src/components/Project/GMS/GMSViewer.js

Non-projects now also comes with error bounds in Mw and Rrup distribution plot
Due to changes in a function deals with download GMS data, need to pass the disaggregation data which currently doesn't exist for non-projects. They are currently on hold. Hence, left a TODO comment for future work.

Mw rrup plot error bounds

---

apis/intermediate_api/intermediate_api/api/intermediate_api.py

Basically a split version of #30.  There will be one more, Project API.
Once three different PRs go through, the `remove_a_few_items` branch should be identical to `update_auth_structure`.
- Must be authenticated via Auth0
- Must have admin permission via Auth0
- One exception, `get_auth0_user_key_info()` this endpoint is for getting a user's information so whoever with Auth0 token will hit this endpoint right after they logged into the application.

Intermediate API updates

---

frontend/CHANGELOG.md
frontend/src/components/Hazard/SeismicHazard/HazardViewerDisaggregation.js
frontend/src/components/Project/SeismicHazard/HazardViewerDisaggregation.js
frontend/src/components/Project/SeismicHazard/HazardViewerHazardCurve.js

- Unlike the disaggregation, UHS, GMS or Scenarios plots, Hazard Curve has extra data that may/may not exist. However, by not resetting them, users may see the NZ code data from a different IM.
- Minor changes - fix the typo
- Location: Wellington Te Papa Museum
- Vs30 - 216m/s
- Z1.0|2.5 - Default
- IM - pSA
- Period - 3.0
- Component - RotD50
- Location: Wellington Te Papa Museum
- Vs30 - 216m/s
- Z1.0|2.5 - Default
- IM - PGV
- Component - RotD50
PGV should not have any NZ code but because the app kept the NZ Code data from the previous request, pSA3.0.

Reset any existing data for Hazard Curve -  NZ code

---

tools/project_gen/project_gen/project.py

Writes as a csv for the z values.
tested with this reader to make sure it's the same format.
https://github.com/ucgmsim/qcore/pull/263

changed the z writer to use the csv format too

---

calculation/gmhazard_calc/gmhazard_calc/directivity/directivity.py

Now only needs to calculate GC2 once for each fault for directivity.
Also combined nominal strike with site coords as they are just site locations and are extracted out after GC2 is calculated.

Moving GC2 out of hypocentre loop

---

calculation/gmhazard_calc/gmhazard_calc/gm_data/Ensemble.py
calculation/gmhazard_calc/gmhazard_calc/gm_data/IMEnsemble.py
calculation/gmhazard_calc/gmhazard_calc/gm_data/Leaf.py

- Added IM lazy loading to both Ensemble and IMEnsemble

Ensemble load fix

---

calculation/gmhazard_calc/gmhazard_calc/uhs/UHSResult.py
frontend/CHANGELOG.md
frontend/src/components/Hazard/SeismicHazard/HazardViewerUHS.js
frontend/src/components/Project/SeismicHazard/HazardViewerUHS.js
frontend/src/components/common/UHS/UHSBranchPlot.js
frontend/src/components/common/UHS/UHSPlot.js

Instead of sending JSON with NaN, convert those to string "nan" to solve an issue with JSON not having the right data type.
UHS only displays if the given data does not include any "nan".

Fix UHS nan issue

---

frontend/CHANGELOG.md
frontend/src/assets/style/Footer.css
frontend/src/components/Hazard/Scenarios/ScenarioForm.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/Project/Scenarios/ScenarioForm.js
frontend/src/constants/Constants.js
frontend/src/views/Footer.js

- External link(to the UC's disclaimer/copyright page) in the footer
- Update the tooltip message for Scenarios
- Temporarily remove the Framework Documents tab.
- As this is still in draft.

Add disclaimer

---

apis/project_api/project_api/api/scenario.py
apis/project_api/project_api/utils.py
frontend/src/assets/style/HazardForms.css
frontend/src/assets/style/ScenarioViewer.css
frontend/src/components/Hazard/SeismicHazard/HazardViewerDisaggregation.js
frontend/src/components/Project/Scenarios/ScenarioViewer.js
frontend/src/components/Project/SeismicHazard/HazardViewerDisaggregation.js
frontend/src/components/common/Scenarios/MetadataTable.js
frontend/src/components/common/index.js

I will work on those tasks after helping Robin.
The scenario now has two tabs, one for plot and another for source contributions, just like the Disaggregation.
- Scenario's dedicated table, which is not a shareable component with Disaggregation
- Minor tidy-up on CSS
- Annual recurrence rate in 4S.F

Scenario with table

---

tools/gmhazard_scripts/db_creation/empirical_db/new_calc_emp_ds.py

This way, we can meet the requirements within the `ensemble_creation` script.
And it managed to create an ensemble_config.yaml file

Create empty DS DB files

---

frontend/package-lock.json
frontend/package.json
frontend/src/views/FrameworkDocView.js
frontend/yarn.lock

Markdown with the following context will render
something like this

Supporting math equation with markdown

---

frontend/src/assets/style/MetadataBox.css
frontend/src/components/Hazard/SeismicHazard/HazardViewerHazardCurve.js
frontend/src/components/Project/SeismicHazard/HazardViewerDisaggregation.js
frontend/src/components/Project/SeismicHazard/HazardViewerHazardCurve.js
frontend/src/components/Project/SeismicHazard/HazardViewerUHS.js
frontend/src/components/common/Disaggregation/ContributionTable.js
frontend/src/components/common/GMS/GMSAvailableGMPlot.js
frontend/src/components/common/GMS/GMSCausalParamPlot.js
frontend/src/components/common/GMS/GMSDisaggDistributionPlot.js
frontend/src/components/common/GMS/GMSIMDistributionsPlot.js
frontend/src/components/common/GMS/GMSMwRrupPlot.js
frontend/src/components/common/GMS/GMSSpectraPlot.js
frontend/src/components/common/HazardCurve/HazardBranchPlot.js
frontend/src/components/common/HazardCurve/HazardEnsemblePlot.js
frontend/src/components/common/HazardCurve/NZTADisclaimerModal.js
frontend/src/components/common/MetadataBox.js
frontend/src/components/common/Scenarios/MetadataTable.js
frontend/src/components/common/Scenarios/ScenarioPlot.js
frontend/src/components/common/SiteSelection/ImageMap.js
frontend/src/components/common/UHS/UHSBranchPlot.js
frontend/src/components/common/UHS/UHSPlot.js
frontend/src/components/common/index.js
frontend/src/constants/Constants.js

1. Implement `memo` to improve performance - Reduced the number of unnecessary re-rendering, especially when you switch between tabs.(E.g., Hazard Curve plot tab, Disaggregation tab as they unmount(kill) the component when the current tab is closed. so when you witch back, the app has to re-render it again even if the data hasn't changed)
2. Change the metadata keys to be constants
3. Using a `switch` to handle multiple conditions within the metadatabox
4. Implemented a modal for Disclaimer to open a modal to give a more detailed reference
(Cursor changes to pointer/hand but on kazam, it is not represented properly.)

NZTA Disclaimer & Fix minor bugs

---

apis/api_utils/api_utils/api/shared.py
calculation/gmhazard_calc/gmhazard_calc/gms/GroundMotionDataset.py
calculation/gmhazard_calc/gmhazard_calc/gms/gms.py
calculation/gmhazard_calc/gmhazard_calc/plots/plt_plotting.py

- A realisation should be based on a single rupture, NOT one rupture per IMi of the realisation.
- Also updated dataframes to have string column names instead of IM objects

Fixed rupture selection bug

---

calculation/sha_calc/sha_calc/gms/shared.py
tools/project_gen/project_gen/gms.py

Extra error details for assert check.

Prevent assert errors from crashing project generation. 

---

frontend/src/components/Project/Scenarios/ScenarioViewer.js
frontend/src/components/common/Scenarios/ScenarioRuptureMetaTable.js

There are only 20 ruptures for now. Hence, we decide to remove the 'Show More' button.

Remove show more button

---

calculation/gmhazard_calc/gmhazard_calc/directivity/bench_data/create_bench.py
calculation/gmhazard_calc/gmhazard_calc/directivity/benchmark_tests.py
calculation/gmhazard_calc/gmhazard_calc/directivity/utils.py
calculation/gmhazard_calc/gmhazard_calc/rupture/__init__.py
calculation/gmhazard_calc/gmhazard_calc/rupture/rupture.py
tools/gmhazard_scripts/db_creation/empirical_db/calc_distances_flt.py

Because of https://github.com/ucgmsim/cybershake_investigation/pull/14

Adding general function to qcore
